name: context and expressions
on:
  workflow_dispatch:
jobs:
  context-expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Describe the run
        run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Event: ${{ github.event_name }}"
        echo "Triggered by: ${{ github.actor }}"
