name: Installing python
on:
  workflow_dispatch:
jobs:
  python_installation:
    runs-on:
    steps:
      - name: clone the repo
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.15"
      - name: check python version
        run: python --version
